inku_app/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='home'),
]

inkuapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'', include('inku_app.urls')),
    url(r'^borrower/', include('borrower_app.urls', namespace='borrower')),
    url(r'^lender/', include('lender_app.urls', namespace='lender')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^loans/', include('loans_app.urls', namespace='loans')),

    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lender_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^deposit/$', views.LenderDepositView.as_view(), name='deposit_loan'),
    url(r'^marketplace/$', views.LenderMarketplaceView.as_view(), name='loan_marketplace'),
    url(r'^my_account/$', views.lender_my_account_view, name='lender_my_account'),
    url(r'^investments/$', views.Investments.as_view(), name='investments'),
]

inku_app/models.py
from django.db import models

# Create your models here.

inku_app/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'inku_app/index.html')

inku_app/templates/inku_app/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="Inku: Small Business Lending" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="Codeply">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}"/>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Ubuntu" />
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />




    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-87388332-1', 'auto');
        ga('send', 'pageview');
    </script>
</head>
<body>
<div class="navbar navbar-fixed-top opaque-navbar">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navMain">
                <span class="glyphicon glyphicon-chevron-right" style="color:white;"></span>

            </button>
            <a class="navbar-brand" href="/"><img src="https://s3.amazonaws.com/inku-background-video/Gray.png" height="40"></a>
        </div>
        <div class="collapse navbar-collapse" id="navMain">
            <ul class="nav navbar-nav pull-right">
                {% if user.is_authenticated %}
                <li><a href = "{% url 'borrower:index' %}" class="button2">borrow</a></li>
                <li><a href = "{% url 'lender:index' %}" class="button2">invest</a></li>
                <li><a href="{% url 'logout' %}" class="button1">logout</a></li>
                {% else %}
                <li><a href = "{% url 'signup_borrower' %}" class="button2">borrow</a></li>
                <li><a href = "{% url 'signup_lender' %}" class="button2">invest</a></li>
                <li><a href="{% url 'login' %}" class="button1">login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>


{% block content %}
{% endblock %}

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.min.js' %}"></script>
<script src="{% static 'js/wow.js' %}"></script>
<script src="{% static 'js/scripts.js' %}"></script>
<script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>

<script type="text/javascript">
    $(function () {
        $('.dtpick').datepicker({
            format: 'yyyy-mm-dd',
            autoclose: true,
            startView: "years",
            endDate: "2006-12-31"
        });
    })
</script>

{% include 'inku_app/messages.html' %}

</body>
</html>

inku_app/templates/inku_app/index.html
{% extends 'inku_app/base.html' %}

{% block title %}Inku{% endblock %}

{% block content %}

<header class=bgPAP2>
        <div class="header-content">
            <div class="header-content-inner">
                <h1 id="homeHeading">Empowered Lending</h1>
                <hr style="width: 50px">
                <h3 class="heading">Bridging the gap to sustainable growth</h3>
            </div>
        </div>
    </header>

   <div class="colorstrip">
    <div class="back2">
    <br>
        <div class="container">
            <div class="row">
        
                     <div class="col-sm-4 text-center">
                       <div class="feature">

                       <img height="70" src="https://s3.amazonaws.com/inku-background-video/line-graph+(1).png">
                       <br><br>
                        <p class="home">Lower Interest Rates</br> for Borrowers</p>
                    </div>
                  </div>
                  <div class="col-sm-4 text-center">
                       <div class="feature">

                       <img height="70"  src= "https://s3.amazonaws.com/inku-background-video/list+(1).png">
                       <br><br>
                        <p class="home">Maximized B-BBEE Points </br>for investors</p>
                    </div>
                  </div>

                  <div class="row">
                     <div class="col-sm-4 text-center">
                       <div class="feature">
                        <img height="70"   src= "https://s3.amazonaws.com/inku-background-video/teamwork+(2).png">
                        <br><br>
                        <p class="home">Supply Chain Development</p>
                    </div>
                    </div>
                   </div>

        </div>
        </div>
        </div>
        </div>

    <section class="back" id="one">
         <div class="header-content"> 
            <div class = "container">
            <div class="row">
                <div class="col-lg-12 text-center">
                <br><br><br><br>
                    <h1 class="text-primary2">
                        Inku is a community for ESD financing, where we provide the platform to connect deserving black-owned businesses and corporate ESD programs.
                    </h1>
                  
                <br><br><br><br><br>
        </div>
        </div>
        <div class="row">
          <div class="col-sm-12">
            <div class="text-center">
              <a class="greenbutton" href = "{% url 'signup_borrower' %}">Borrow</a>
              &nbsp;
              &nbsp;
              <a class="bluebutton" href = "{% url 'signup_lender' %}">Invest</a>
            </div>
          </div>
        </div>
        </div>
              
        </div>
        </div>
    </section>



   <div class="colorstrip">
    <div class="back2">
    <br>
        <div class="container">
             <div class="col-lg-12 text-center">
                    <h2 class="text-primaryL">How it Works</h2>
                    <br><br>
         <div class="row">
            <div class="col-sm-1 text-center">
                 <div class="feature">

                       <img height="70" src="https://s3.amazonaws.com/inku-background-video/note+(1).png">
                       <br><br>
                       <p class="home">Borrower Applies</p>
                    </div>
            </div>
            <div class="col-sm-1 text-center">
             <div class="feature">
                        <br><br>
                       <img height="40" src="https://s3.amazonaws.com/inku-background-video/next.png">
                
                    </div>
            </div>
            <div class="col-sm-1 text-center">
                 <div class="feature">

                       <img height="70" src="https://s3.amazonaws.com/inku-background-video/search+(1).png">
                       <br><br>
                       <p class="home">Assess Application</p>
                    </div>
            </div>
             <div class="col-sm-1 text-center">
             <div class="feature">
                        <br><br>
                       <img height="40" src="https://s3.amazonaws.com/inku-background-video/next.png">
                
                    </div>
            </div>
            <div class="col-sm-1 text-center">
                 <div class="feature">

                       <img height="70" src="https://s3.amazonaws.com/inku-background-video/checked+(2).png">
                       <br><br>
                        <p class="home">Post to </br>marketplace</p>
                    </div>
            </div>
             <div class="col-sm-1 text-center">
             <div class="feature">
                        <br><br>
                       <img height="40" src="https://s3.amazonaws.com/inku-background-video/next.png">
                
                    </div>
            </div>
            <div class="col-sm-1 text-center">
                 <div class="feature">

                       <img height="70" src="https://s3.amazonaws.com/inku-background-video/checked+(3).png">
                       <br><br>
                        <p class="home">Funded by</br> investor</p>
                    </div>
            </div>
              <div class="col-sm-1 text-center">
             <div class="feature">
                        <br><br>
                       <img height="40" src="https://s3.amazonaws.com/inku-background-video/next.png">
                
                    </div>
            </div>
            <div class="col-sm-1 text-center">
                 <div class="feature">

                       <img height="70" src="https://s3.amazonaws.com/inku-background-video/network+(1).png">
                       <br><br>
                        <p class="home">Monthly repayments</p>
                    </div>
            </div>

             <div class="col-sm-1 text-center">
             <div class="feature">
                        <br><br>
                       <img height="40" src="https://s3.amazonaws.com/inku-background-video/next.png">
                
                    </div>
            </div>
            <div class="col-sm-1 text-center">
                 <div class="feature">
                       <img height="70" src="https://s3.amazonaws.com/inku-background-video/teamwork+(3).png">
                       <br><br>
                        <p class="home">Earn ESD points</p>
                    </div>
            </div>
        </div>
        <br><br>  
        </div>
        </div>
        </div>
  
        <section class="back" id="one">
         <div class="header-content"> 
            <div class = "container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h1 class="text-primary">
                       Contact Us
                    </h1>
                    <h1 class="text-primary2">join@inku.io</h2>
            
                <br><br><br><br>
        </div>
        </div>
       
              
        </div>
        </div>
    </section>
  






{% endblock %}

inku_app/templates/inku_app/messages.html
{% if messages %}
    <!-- Modal -->
    <div class="modal fade" id="modalWindow" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    {#                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>#}
                    {#                        <h4 class="modal-title" id="modalWindowTitle"></h4>#}
                </div>
                <div class="modal-body">
                    {% for message in messages %}
                        <h3>{{ message }}</h3>
                    {% endfor %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#modalWindow').modal('show');
        });
    </script>
{% endif %}