borrower_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^request_loan/$', views.RequestLoanView.as_view(), name='request_loan'),
]

inkuapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'', include('inku_app.urls')),
    url(r'^borrower/', include('borrower_app.urls', namespace='borrower')),
    url(r'^lender/', include('lender_app.urls', namespace='lender')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^loans/', include('loans_app.urls', namespace='loans')),

    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

borrower_app/forms.py
from django import forms
from loans_app.models import LoanRequest


class RequestLoanForm(forms.ModelForm):
    class Meta:
        model = LoanRequest
        fields = '__all__'
        # We don't want to show a user choice but we still need prefill borrower field in view
        exclude = ['borrower', 'request_status', 'started_at', 'remaining_amount', 'average_interest_rate', 'inku_score']

borrower_app/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import CreateView
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.contrib.auth import get_user_model

from inku_app.decorators import user_is_borrower
from .forms import RequestLoanForm

user_model = get_user_model()
decorators = [login_required, user_is_borrower]


@login_required
@user_is_borrower
def index(request):
    return render(request, 'borrower_app/index.html')


@method_decorator(decorators, name='dispatch')
class RequestLoanView(CreateView):
    template_name = 'borrower_app/request_loan.html'
    form_class = RequestLoanForm
    success_url = reverse_lazy('borrower:index')

    def form_valid(self, form):
        # Apply form's borrower field based on current user
        user = self.request.user
        form.instance.borrower = user
        form.save()
        messages.success(self.request, "Loan Request Submitted")
        return super(RequestLoanView, self).form_valid(form)

    # Pre-fill initial data for borrower field
    def get_initial(self):
        borrower = get_object_or_404(user_model, pk=self.request.user.pk)
        return {
            'borrower': borrower,
        }

borrower_app/templates/borrower_app/index.html
{% extends 'inku_app/base.html' %}

{% block title %}
    Borrower portal main page
{% endblock %}

{% block content %}
    <section class="services2">
        <div class="container">
            <div class="col-lg-12 text-center">
                <img src="https://s3.amazonaws.com/inku-background-video/green+with+gray.png" height="200">
                <br>
                
                <br><br><br>
                <div class="col-lg-12 text-center">
                    <a href="{% url 'borrower:request_loan' %}" class="signupbutton btn btn-info btn-lg" role="button">Apply for loan</a>
                    <a href="#" class="signupbutton btn btn-info btn-lg" role="button">My Account</a>
                </div>
            </div>
            <div>
            </div>
        </div>
    </section>
{% endblock %}

borrower_app/templates/borrower_app/request_loan.html
{% extends 'inku_app/base.html' %}
{% load widget_tweaks %}

{% block title %}
    Inku - Request loan
{% endblock %}

{% block content %}
    <section class="services2">
        <div class="container">
            <div class="col-md-8 col-md-offset-2">
                <h2 class="margin-top-0 text-dark">Borrower request loan page</h2>
                <br>
                <br>
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active"><a href="#loan_data" aria-controls="loan_data" role="tab" data-toggle="tab">Loan info</a></li>
                    <li role="presentation"><a href="#bank_info" aria-controls="bank_info" role="tab" data-toggle="tab">Bank info</a></li>
                    <li role="presentation"><a href="#documents" aria-controls="documents" role="tab" data-toggle="tab">Documents</a></li>
                    <li role="presentation"><a href="#company_info" aria-controls="company_info" role="tab" data-toggle="tab">Company info</a></li>
                </ul>

                <form class="form-horizontal" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for error in form.non_field_errors %}
                        <p class="help-block">{{ error }}</p>
                    {% endfor %}

                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane active" id="loan_data">
                            <br>
                            <div class="row">
                                <div class="form-group">
                                    <label for="{{ form.business_sector.id_for_label }}">{{ form.business_sector.label }}</label>
                                    {% render_field form.business_sector placeholder=form.business_sector.label class="form-control" %}
                                    {% for error in form.business_sector.errors %}
                                        <span class="help-block">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group">
                                    <label for="{{ form.loan_amount.id_for_label }}">{{ form.loan_amount.label }}</label>
                                    {% render_field form.loan_amount placeholder=form.loan_amount.label class="form-control" %}
                                    {% for error in form.loan_amount.errors %}
                                        <span class="help-block">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group">
                                    <label for="{{ form.term.id_for_label }}">{{ form.term.label }}</label>
                                    {% render_field form.term placeholder=form.term.label class="form-control" %}
                                    {% for error in form.term.errors %}
                                        <span class="help-block">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group">
                                    <label for="{{ form.purpose.id_for_label }}">{{ form.purpose.label }}</label>
                                    {% render_field form.purpose placeholder=form.purpose.label class="form-control" %}
                                    {% for error in form.purpose.errors %}
                                        <span class="help-block">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group">
                                    <label for="{{ form.bridge_finance.id_for_label }}">{{ form.bridge_finance.label }}</label>
                                    {% render_field form.bridge_finance placeholder=form.bridge_finance.label class="form-control" %}
                                    {% for error in form.bridge_finance.errors %}
                                        <span class="help-block">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>

                        <div role="tabpanel" class="tab-pane" id="bank_info">
                            <br>
                            <div class="row">
                                <div class="form-group">
                                    <label for="{{ form.bank_name.id_for_label }}">{{ form.bank_name.label }}</label>
                                    {% render_field form.bank_name placeholder=form.bank_name.label class="form-control" %}
                                    {% for error in form.bank_name.errors %}
                                        <span class="help-block">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group">
                                    <label for="{{ form.branch_code.id_for_label }}">{{ form.branch_code.label }}</label>
                                    {% render_field form.branch_code placeholder=form.branch_code.label class="form-control" %}
                                    {% for error in form.branch_code.errors %}
                                        <span class="help-block">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group">
                                    <label for="{{ form.account_number.id_for_label }}">{{ form.account_number.label }}</label>
                                    {% render_field form.account_number placeholder=form.account_number.label class="form-control" %}
                                    {% for error in form.account_number.errors %}
                                        <span class="help-block">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div role="tabpanel" class="tab-pane" id="documents">
                            <br>
                            <div class="row">
                                <div class="form-group">
                                    <label for="{{ form.founding_statement.id_for_label }}">{{ form.founding_statement.label }}</label>
                                    {% render_field form.founding_statement placeholder=form.founding_statement.label class="form-control" %}
                                    {% for error in form.founding_statement.errors %}
                                        <span class="help-block">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group">
                                    <label for="{{ form.bank_statement.id_for_label }}">{{ form.bank_statement.label }}</label>
                                    {% render_field form.bank_statement placeholder=form.bank_statement.label class="form-control" %}
                                    {% for error in form.bank_statement.errors %}
                                        <span class="help-block">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group">
                                    <label for="{{ form.bar_coded_idd.id_for_label }}">{{ form.bar_coded_idd.label }}</label>
                                    {% render_field form.bar_coded_idd placeholder=form.bar_coded_idd.label class="form-control" %}
                                    {% for error in form.bar_coded_idd.errors %}
                                        <span class="help-block">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div role="tabpanel" class="tab-pane" id="company_info">
                            <br>
                            <div class="row">
                                <div class="form-group">
                                    <label for="{{ form.picture_of_business.id_for_label }}">{{ form.picture_of_business.label }}</label>
                                    {% render_field form.picture_of_business placeholder=form.picture_of_business.label class="form-control" %}
                                    {% for error in form.picture_of_business.errors %}
                                        <span class="help-block">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group">
                                    <label for="{{ form.description.id_for_label }}">{{ form.description.label }}</label>
                                    {% render_field form.description placeholder=form.description.label class="form-control" %}
                                    {% for error in form.description.errors %}
                                        <span class="help-block">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group">
                                    <label for="{{ form.black_ownership_percent.id_for_label }}">{{ form.black_ownership_percent.label }}</label>
                                    {% render_field form.black_ownership_percent placeholder=form.black_ownership_percent.label class="form-control" %}
                                    {% for error in form.black_ownership_percent.errors %}
                                        <span class="help-block">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <br>
                    <br>
                    <div class="row">
                        <div class="form-group">
                            <button type="submit" class="btn btn-success">
                                Submit request
                            </button>
                            <a href="{% url 'borrower:index' %}" class="btn btn-default">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock %}