inkuapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'', include('inku_app.urls')),
    url(r'^borrower/', include('borrower_app.urls', namespace='borrower')),
    url(r'^lender/', include('lender_app.urls', namespace='lender')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^loans/', include('loans_app.urls', namespace='loans')),

    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lender_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^deposit/$', views.LenderDepositView.as_view(), name='deposit_loan'),
    url(r'^marketplace/$', views.LenderMarketplaceView.as_view(), name='loan_marketplace'),
    url(r'^my_account/$', views.lender_my_account_view, name='lender_my_account'),
    url(r'^investments/$', views.Investments.as_view(), name='investments'),
]

loans_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', views.Loanpage.as_view(), name='loan_request_details')
]

lender_app/models.py
from django.db import models
from django.conf import settings

user_model = settings.AUTH_USER_MODEL


class LenderDeposit(models.Model):
    lender = models.ForeignKey(user_model, related_name='deposits', verbose_name='Lender email')
    bank_name = models.CharField(max_length=255)
    branch_code = models.CharField(max_length=50)
    account_number = models.CharField(max_length=50)
    fund_amount = models.PositiveIntegerField()

    def __str__(self):
        return self.lender.email

lender_app/forms.py
from django import forms
from .models import LenderDeposit


class LenderDepositForm(forms.ModelForm):
    class Meta:
        model = LenderDeposit
        fields = '__all__'
        exclude = ['lender']

lender_app/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView
from django.utils.decorators import method_decorator

from inku_app.decorators import user_is_lender

from .forms import LenderDepositForm
from loans_app.models import LoanRequest

user_model = get_user_model()
decorators = [login_required, user_is_lender]


@login_required
@user_is_lender
def index(request):
    return render(request, 'lender_app/index.html')


@method_decorator(decorators, name='dispatch')  # Apply decorators to dispatch CBV method
class LenderDepositView(CreateView):
    template_name = 'lender_app/deposit.html'
    form_class = LenderDepositForm
    success_url = reverse_lazy('lender:index')

    # Pre-fill initial data for lender field
    def get_initial(self):
        lender = get_object_or_404(user_model, pk=self.request.user.pk)
        return {
            'lender': lender,
        }

    def form_valid(self, form):
        # Apply form's lender field based on current user
        form.instance.lender = self.request.user
        form.save()
        messages.success(self.request, 'Deposit Request Submitted')
        return super(LenderDepositView, self).form_valid(form)


class LenderMarketplaceView(ListView):
    template_name = 'lender_app/loan_marketplace.html'
    model = LoanRequest
    context_object_name = "loan_requests"
    queryset = LoanRequest.objects.exclude(request_status=0)


def lender_my_account_view(request):
    return render(request, 'lender_app/my_account.html')


class Investments(ListView):
    template_name = 'lender_app/investments.html'
    model = LoanRequest

lender_app/templates/lender_app/deposit.html
{% extends 'inku_app/base.html' %}
{% load widget_tweaks %}

{% block title %}
    Inku - Deposit loan
{% endblock %}

{% block content %}
    <section class="services2">
        <div class="container">
            <div class="col-md-4 col-md-offset-4">
                <h2 class="margin-top-0 text-dark">Lender deposit loan page</h2>
                <br>
                <br>
                <form class="form-horizontal" method="POST">
                    {% csrf_token %}
                    {% for error in form.non_field_errors %}
                        <p class="help-block">{{ error }}</p>
                    {% endfor %}

                    {% for field in form %}
                        <div class="row">
                            <div class="form-group">
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {% render_field field placeholder=field.label class="form-control" %}
                                {% for error in field.errors %}
                                    <span class="help-block">{{ error }}</span>
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}

                    <div class="row">
                        <div class="form-group">
                            <button type="submit" class="btn btn-success">
                                Submit request
                            </button>
                            <a href="{% url 'lender:index' %}" class="btn btn-default">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
            <div>
            </div>
        </div>
    </section>
{% endblock %}

lender_app/templates/lender_app/index.html
{% extends 'inku_app/base.html' %}

{% block title %}
    Lender portal main page
{% endblock %}

{% block content %}
    <section class="services2">
        <div class="container">
            <div class="col-lg-12 text-center">
                <img src="https://s3.amazonaws.com/inku-background-video/Blue+With+Gray+Logo.png" height="200">
                <br><br>
                <h1 class="margin-top-0 text-dark">Lender Portal</h1>
                <br><br><br>
                <br>
                <div class="col-lg-12 text-center">
                    <a href="{% url 'lender:loan_marketplace' %}" class="lendersignup btn btn-info btn-lg" role="button">Marketplace</a>
                    <a href="{% url 'lender:lender_my_account' %}" class="lendersignup btn btn-info btn-lg" role="button">My Account</a>
                    <a href="{% url 'lender:deposit_loan' %}" class="lendersignup btn btn-info btn-lg" role="button">Deposit</a>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

lender_app/templates/lender_app/investments.html
{% extends 'inku_app/base.html' %}
{% load widget_tweaks %}

{% block title %}
    Inku - Deposit loan
{% endblock %}

{% block content %}
<section class="bgPAP">
  

    <div class= "container">
    <div class= "row">

   
      <h1 style="font-size:43px; font-weight:300">Investments</h1>

      <hr width="30%" class="dark">
      <div class="container">
      <br>
  <div class="row seven-cols">
  <div class="investmentrow">
    <div class="col-md-1">
      <h2 class="accountpage">Business Name</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage">Loan Principal</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage">Issue Date</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage">Status</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage">Total Paid</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage">Next Payment</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage">Interest Rate</h2>
    </div>
    </div>
  </div>
    <div class="row seven-cols">
  <div class="investmentrow2">
    <div class="col-md-1">
     <a  class="text-center" id="clickMe"><br><br><br>View More</a>
      <h2 class="accountpage2">Jeff's Welding Co.</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">R150,000.00</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">January 18th, 2017</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">Outstanding</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">R47,000.00</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">May 18th, 2017</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">3.4%</h2>
    </div>
    </div>
  </div>
    <div class="row seven-cols">
  <div class="investmentrow2">
    <div class="col-md-1">
      <h2 class="accountpage2">Jeff's Welding Co.</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">R150,000.00</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">January 18th, 2017</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">Outstanding</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">R47,000.00</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">May 18th, 2017</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">3.4%</h2>
    </div>
    </div>
  </div>
    <div class="row seven-cols">
  <div class="investmentrow2">
    <div class="col-md-1">
      <h2 class="accountpage2">Jeff's Welding Co.</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">R150,000.00</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">January 18th, 2017</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">Outstanding</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">R47,000.00</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">May 18th, 2017</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">3.4%</h2>
    </div>
    </div>
  </div>
    <div class="row seven-cols">
  <div class="investmentrow2">
    <div class="col-md-1">
      <h2 class="accountpage2">Jeff's Welding Co.</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">R150,000.00</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">January 18th, 2017</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">Outstanding</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">R47,000.00</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">May 18th, 2017</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">3.4%</h2>
    </div>
    </div>
  </div>
    <div class="row seven-cols">
  <div class="investmentrow2">

    <div class="col-md-1">
      <h2 class="accountpage2">Jeff's Welding Co.</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">R150,000.00</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">January 18th, 2017</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">Outstanding</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">R47,000.00</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">May 18th, 2017</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">3.4%</h2>
    </div>
    </div>
  </div>
    <div class="row seven-cols">
  <div class="investmentrow2">
    <div class="col-md-1">
      <h2 class="accountpage2">Jeff's Welding Co.</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">R150,000.00</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">January 18th, 2017</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">Outstanding</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">R47,000.00</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">May 18th, 2017</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">3.4%</h2>
    </div>
    </div>
  </div>
    <div class="row seven-cols">
  <div class="investmentrow2">
    <div class="col-md-1">
      <h2 class="accountpage2">Jeff's Welding Co.</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">R150,000.00</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">January 18th, 2017</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">Outstanding</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">R47,000.00</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">May 18th, 2017</h2>
    </div>
    <div class="col-md-1">
      <h2 class="accountpage2">3.4%</h2>
    </div>
    </div>
  </div>
</div>
      
    </div>
    <br><br>

 
     </div>


  
 
    </section>

    {% endblock %}

lender_app/templates/lender_app/loan_marketplace.html
{% extends 'inku_app/base.html' %}
{% load humanize common_tags %}

{% block title %}Inku{% endblock %}

{% block content %}

    <script type="text/javascript">
        function openNav() {
            document.getElementById("mySidenav").style.width = "300px";
            document.getElementById("main").style.marginLeft = "300px";
            document.body.style.backgroundColor = "rgba(0,0,0,0.4)";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
            document.getElementById("main").style.marginLeft= "0";
            document.body.style.backgroundColor = "white";
        }
    </script>

    <section class="bgPAP">
        <div class= "container">
            <!-- Filters -->
            <div class= "row">
                <div id="mySidenav" class="sidenav">
                    <h2 class="nav">&#9776;&nbsp;Filters</h2>
                    <br>
                    <h3 class="navside">Industry</h3>
                    <hr class="dark2">
                    <div class="border row">
                        <div class="border col-md-6">
                            <div class="inputleft">
                                <form>
                                    <div class="checkbox">
                                        <label><input type="checkbox" value="">Retail</label>
                                    </div>
                                    <div class="checkbox">
                                        <label><input type="checkbox" value="">Manufacturing</label>
                                    </div>
                                    <div class="checkbox">
                                        <label><input type="checkbox" value="">Wholesale</label>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="border col-md-6">
                            <div class="inputleft">
                                <form>
                                    <div class="checkbox">
                                        <label><input type="checkbox" value="">Agriculture</label>
                                    </div>
                                    <div class="checkbox">
                                        <label><input type="checkbox" value="">Construction</label>
                                    </div>
                                    <div class="checkbox">
                                        <label><input type="checkbox" value="">Services</label>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>

                    <h3 class="navside">Term</h3>
                    <hr class="dark2">
                    <div class="border row">
                        <div class="border col-md-6">
                            <div class="inputleft">
                                <form>
                                    <div class="checkbox">
                                        <label><input type="checkbox" value="">&lt; 12 Months</label>
                                    </div>
                                    <div class="checkbox">
                                        <label><input type="checkbox" value="">12 Months</label>
                                    </div>

                                </form>
                            </div>

                        </div>
                        <div class="border col-md-6">
                            <div class="inputleft">
                                <form>
                                    <div class="checkbox">
                                        <label><input type="checkbox" value="">18 Months</label>
                                    </div>
                                    <div class="checkbox">
                                        <label><input type="checkbox" value="">>24 Months</label>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>

                    <h3 class="navside">Inku Score</h3>
                    <hr class="dark2">
                    <div class="border row">
                        <div class="border col-md-6">
                            <div class="inputleft">
                                <form>
                                    <div class="checkbox">
                                        <label><input type="checkbox" value="">A</label>
                                    </div>
                                    <div class="checkbox">
                                        <label><input type="checkbox" value="">B</label>
                                    </div>

                                </form>
                            </div>

                        </div>
                        <div class="border col-md-6">
                            <div class="inputleft">
                                <form>
                                    <div class="checkbox">
                                        <label><input type="checkbox" value="">C</label>
                                    </div>
                                    <div class="checkbox">
                                        <label><input type="checkbox" value="">D</label>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                    <hr class="dark2">
                    <br><br><br><br>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="text-center">
                                <span class="navbutton" style="cursor:pointer" onclick="closeNav()">Apply</span>
                                &nbsp;
                                &nbsp;
                                <span class="navbutton" style="cursor:pointer" onclick="closeNav()">Close</span>
                            </div>
                        </div>
                    </div>
                </div>

                <span class="filterbutton" style="cursor:pointer" onclick="openNav()">&#9776;  Filters</span>

                <select class=filterstemp>
                    <option value="" disabled selected>Sort By</option>
                    <option value="2">Time</option>
                    <option value="3">Interest</option>
                    <option value="4">Inku Score</option>
                    <option value="5">Term</option>
                    <option value="6">Principal</option>
                </select>

                <h1 style="font-size:43px; font-weight:100">Marketplace</h1>

                <hr width="90%" class="dark">
            </div>

            <!-- Loan request items -->
            <div class="row">
                {% for loan_request in loan_requests %}
                    <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                        <div class="loan">
                            <a href="{% url 'loans:loan_request_details' loan_request.pk %}" class="text-center" id="clickMe"><br><br><br>View More</a>

                            <div class="countdown">
                                <p style="color:#444647">{{ loan_request.end_at_date|loan_reqest_remaining_time }}</p>
                            </div>
                            <div class="loanpic">
                                <img src="{{ loan_request.picture_of_business.url }}" width="100%">
                            </div>
                            <div class="loantag">
                                <h3 class="auction">{{ loan_request.borrower.business_name }}</h3>
                                <p class="auction2">{{ loan_request.purpose }}</p>
                            </div>
                            <hr class="dark">
                            <div class="littlebox">
                                <div class="col-xs-4 text-center verticalright">
                                    <h3 class="auction2">Inku Score</h3>
                                    <h1 class="auction">{{ loan_request.inku_score }}</h1>
                                </div>
                                <div class="col-xs-4 text-center verticalright">
                                    <h3 class="auction2">Int. Rate</h3>
                                    <h1 class="auction2">{{ loan_request.average_interest_rate }}%</h1>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <h3 class="auction2">Term(Months)</h3>
                                    <h1 class="auction">{{ loan_request.term }}</h1>
                                </div>
                            </div>
                            <hr class="dark">
                            <div class="loanfill">
                                <div class="loanload text-left" style="width:60%">
                                    <h3 class="light">R{{ loan_request.remaining_amount|intcomma }} Remaining</h3>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

lender_app/templates/lender_app/my_account.html
{% extends 'inku_app/base.html' %}

{% block title %}
    Lender my account page
{% endblock %}

{% block content %}
    <section class="bgPAP">


        <div class= "container">
            <div class= "row">


                <h1 style="font-size:43px; font-weight:300">Account Summary</h1>

                <hr width="30%" class="dark">

            </div>
            <br><br>

            <div class="border row">
                <div class="border col-md-3">
                    <div class="accountbox">
                        <h1 class="accountpage">Available Cash</h1>
                        <br>
                        <h1 class="accountpage3">R144,321.12</h1>
                    </div>
                </div>
                <div class="border col-md-3">
                    <div class="accountbox">
                        <h1 class="accountpage">ESD Contribution</h1>
                        <br>
                        <h1 class="accountpage3">R3,000,000.00</h1>
                    </div>
                </div>
                <div class="border col-md-3">
                    <div class="accountbox">
                        <h1 class="accountpage">Avg. Benefit Factor</h1>
                        <br>
                        <h1 class="accountpage3">58.3%</h1>
                    </div>
                </div>
                <div class="border col-md-3">
                    <div class="accountbox">
                        <h1 class="accountpage">Net Annualized Returns</h1>
                        <br>
                        <h1 class="accountpage3">3.4%</h1>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8">

                    <div class="accountbox2">
                        <h1 class="accountpage">My Account:</h1>
                        <div class="border col-md-6">
                            <h1 class="accountpage2">Available Cash:</h1>
                            <h1 class="accountpage2">Committed Cash:</h1>
                            <h1 class="accountpage2">Outstanding Principal:</h1>
                            <br>

                        </div>
                        <div class="border col-md-6">
                            <h1 class="accountpage4">R144,321.12</h1>
                            <h1 class="accountpage4">R75,331.00</h1>
                            <h1 class="accountpage4">R200,313.11</h1>


                        </div>
                        <hr width="80%" class="dark">
                        <br>
                        <h1 class="accountpage2">Account Value:   &nbsp;   &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;
                            &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;
                            &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;    R3,000,000.00</h1>

                    </div>
                </div>

                <div class="col-sm-4">
                    <div class="accountbox2">
                        <h1 class="accountpage">Investments</h1>
                        <div class="border row">


                            <div class="border col-md-6">
                                <h3 class="accountpage">Not Yet Issued:</h3>
                                <h3 class="accountpage">Current:</h3>
                                <h3 class="accountpage">Fully Paid:</h3>
                                <h3 class="accountpage">Late(16-31 Days):</h3>
                                <h3 class="accountpage">Late(31-120 Days):</h3>
                                <h3 class="accountpage">Default:</h3>
                                <h3 class="accountpage">Prepayment:</h3>
                            </div>
                            <div class="border col-md-6">
                                <h3 class="accountpage2">2</h3>
                                <h3 class="accountpage2">4</h3>
                                <h3 class="accountpage2">3</h3>
                                <h3 class="accountpage2">1</h3>
                                <h3 class="accountpage2">0</h3>
                                <h3 class="accountpage2">1</h3>
                                <h3 class="accountpage2">0</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <br><br>
            <div class="row">
                <a href="{% url 'lender:investments' %}" class="bluebutton">Browse Investments</a>
                <a href="{% url 'lender:deposit_loan' %}" class="bluebutton">Add Funds</a>
                <a href="{% url 'lender:loan_marketplace' %}" class="bluebutton">Lending Options</a>
            </div>
        </div>
    </section>

{% endblock %}